const countries = [
    { "CountryName": "Afghanistan", "Code": "AF" },
    { "CountryName": "Åland Islands", "Code": "AX" },
    { "CountryName": "Albania", "Code": "AL" },
    { "CountryName": "Algeria", "Code": "DZ" },
    { "CountryName": "American Samoa", "Code": "AS" },
    { "CountryName": "Andorra", "Code": "AD" },
    { "CountryName": "Angola", "Code": "AO" },
    { "CountryName": "Anguilla", "Code": "AI" },
    { "CountryName": "Antarctica", "Code": "AQ" },
    { "CountryName": "Antigua and Barbuda", "Code": "AG" },
    { "CountryName": "Argentina", "Code": "AR" },
    { "CountryName": "Armenia", "Code": "AM" },
    { "CountryName": "Aruba", "Code": "AW" },
    { "CountryName": "Australia", "Code": "AU" },
    { "CountryName": "Austria", "Code": "AT" },
    { "CountryName": "Azerbaijan", "Code": "AZ" },
    { "CountryName": "Bahamas", "Code": "BS" },
    { "CountryName": "Bahrain", "Code": "BH" },
    { "CountryName": "Bangladesh", "Code": "BD" },
    { "CountryName": "Barbados", "Code": "BB" },
    { "CountryName": "Belarus", "Code": "BY" },
    { "CountryName": "Belgium", "Code": "BE" },
    { "CountryName": "Belize", "Code": "BZ" },
    { "CountryName": "Benin", "Code": "BJ" },
    { "CountryName": "Bermuda", "Code": "BM" },
    { "CountryName": "Bhutan", "Code": "BT" },
    { "CountryName": "Bolivia (Plurinational State of)", "Code": "BO" },
    { "CountryName": "Bonaire, Sint Eustatius and Saba", "Code": "BQ" },
    { "CountryName": "Bosnia and Herzegovina", "Code": "BA" },
    { "CountryName": "Botswana", "Code": "BW" },
    { "CountryName": "Bouvet Island", "Code": "BV" },
    { "CountryName": "Brazil", "Code": "BR" },
    { "CountryName": "British Indian Ocean Territory", "Code": "IO" },
    { "CountryName": "Brunei Darussalam", "Code": "BN" },
    { "CountryName": "Bulgaria", "Code": "BG" },
    { "CountryName": "Burkina Faso", "Code": "BF" },
    { "CountryName": "Burundi", "Code": "BI" },
    { "CountryName": "Cabo Verde", "Code": "CV" },
    { "CountryName": "Cambodia", "Code": "KH" },
    { "CountryName": "Cameroon", "Code": "CM" },
    { "CountryName": "Canada", "Code": "CA" },
    { "CountryName": "Cayman Islands", "Code": "KY" },
    { "CountryName": "Central African Republic", "Code": "CF" },
    { "CountryName": "Chad", "Code": "TD" },
    { "CountryName": "Chile", "Code": "CL" },
    { "CountryName": "China", "Code": "CN" },
    { "CountryName": "Christmas Island", "Code": "CX" },
    { "CountryName": "Cocos (Keeling) Islands", "Code": "CC" },
    { "CountryName": "Colombia", "Code": "CO" },
    { "CountryName": "Comoros", "Code": "KM" },
    { "CountryName": "Congo", "Code": "CG" },
    { "CountryName": "Congo (Democratic Republic of the)", "Code": "CD" },
    { "CountryName": "Cook Islands", "Code": "CK" },
    { "CountryName": "Costa Rica", "Code": "CR" },
    { "CountryName": "Côte d'Ivoire", "Code": "CI" },
    { "CountryName": "Croatia", "Code": "HR" },
    { "CountryName": "Cuba", "Code": "CU" },
    { "CountryName": "Curaçao", "Code": "CW" },
    { "CountryName": "Cyprus", "Code": "CY" },
    { "CountryName": "Czech Republic", "Code": "CZ" },
    { "CountryName": "Denmark", "Code": "DK" },
    { "CountryName": "Djibouti", "Code": "DJ" },
    { "CountryName": "Dominica", "Code": "DM" },
    { "CountryName": "Dominican Republic", "Code": "DO" },
    { "CountryName": "Ecuador", "Code": "EC" },
    { "CountryName": "Egypt", "Code": "EG" },
    { "CountryName": "El Salvador", "Code": "SV" },
    { "CountryName": "Equatorial Guinea", "Code": "GQ" },
    { "CountryName": "Eritrea", "Code": "ER" },
    { "CountryName": "Estonia", "Code": "EE" },
    { "CountryName": "Ethiopia", "Code": "ET" },
    { "CountryName": "Falkland Islands (Malvinas)", "Code": "FK" },
    { "CountryName": "Faroe Islands", "Code": "FO" },
    { "CountryName": "Fiji", "Code": "FJ" },
    { "CountryName": "Finland", "Code": "FI" },
    { "CountryName": "France", "Code": "FR" },
    { "CountryName": "French Guiana", "Code": "GF" },
    { "CountryName": "French Polynesia", "Code": "PF" },
    { "CountryName": "French Southern Territories", "Code": "TF" },
    { "CountryName": "Gabon", "Code": "GA" },
    { "CountryName": "Gambia", "Code": "GM" },
    { "CountryName": "Georgia", "Code": "GE" },
    { "CountryName": "Germany", "Code": "DE" },
    { "CountryName": "Ghana", "Code": "GH" },
    { "CountryName": "Gibraltar", "Code": "GI" },
    { "CountryName": "Greece", "Code": "GR" },
    { "CountryName": "Greenland", "Code": "GL" },
    { "CountryName": "Grenada", "Code": "GD" },
    { "CountryName": "Guadeloupe", "Code": "GP" },
    { "CountryName": "Guam", "Code": "GU" },
    { "CountryName": "Guatemala", "Code": "GT" },
    { "CountryName": "Guernsey", "Code": "GG" },
    { "CountryName": "Guinea", "Code": "GN" },
    { "CountryName": "Guinea-Bissau", "Code": "GW" },
    { "CountryName": "Guyana", "Code": "GY" },
    { "CountryName": "Haiti", "Code": "HT" },
    { "CountryName": "Heard Island and McDonald Islands", "Code": "HM" },
    { "CountryName": "Holy See", "Code": "VA" },
    { "CountryName": "Honduras", "Code": "HN" },
    { "CountryName": "Hong Kong", "Code": "HK" },
    { "CountryName": "Hungary", "Code": "HU" },
    { "CountryName": "Iceland", "Code": "IS" },
    { "CountryName": "India", "Code": "IN" },
    { "CountryName": "Indonesia", "Code": "ID" },
    { "CountryName": "Iran (Islamic Republic of)", "Code": "IR" },
    { "CountryName": "Iraq", "Code": "IQ" },
    { "CountryName": "Ireland", "Code": "IE" },
    { "CountryName": "Isle of Man", "Code": "IM" },
    { "CountryName": "Israel", "Code": "IL" },
    { "CountryName": "Italy", "Code": "IT" },
    { "CountryName": "Jamaica", "Code": "JM" },
    { "CountryName": "Japan", "Code": "JP" },
    { "CountryName": "Jersey", "Code": "JE" },
    { "CountryName": "Jordan", "Code": "JO" },
    { "CountryName": "Kazakhstan", "Code": "KZ" },
    { "CountryName": "Kenya", "Code": "KE" },
    { "CountryName": "Kiribati", "Code": "KI" },
    { "CountryName": "Korea (Democratic People's Republic of)", "Code": "KP" },
    { "CountryName": "Korea (Republic of)", "Code": "KR" },
    { "CountryName": "Kuwait", "Code": "KW" },
    { "CountryName": "Kyrgyzstan", "Code": "KG" },
    { "CountryName": "Lao People's Democratic Republic", "Code": "LA" },
    { "CountryName": "Latvia", "Code": "LV" },
    { "CountryName": "Lebanon", "Code": "LB" },
    { "CountryName": "Lesotho", "Code": "LS" },
    { "CountryName": "Liberia", "Code": "LR" },
    { "CountryName": "Libya", "Code": "LY" },
    { "CountryName": "Liechtenstein", "Code": "LI" },
    { "CountryName": "Lithuania", "Code": "LT" },
    { "CountryName": "Luxembourg", "Code": "LU" },
    { "CountryName": "Macao", "Code": "MO" },
    { "CountryName": "Macedonia (the former Yugoslav Republic of)", "Code": "MK" },
    { "CountryName": "Madagascar", "Code": "MG" },
    { "CountryName": "Malawi", "Code": "MW" },
    { "CountryName": "Malaysia", "Code": "MY" },
    { "CountryName": "Maldives", "Code": "MV" },
    { "CountryName": "Mali", "Code": "ML" },
    { "CountryName": "Malta", "Code": "MT" },
    { "CountryName": "Marshall Islands", "Code": "MH" },
    { "CountryName": "Martinique", "Code": "MQ" },
    { "CountryName": "Mauritania", "Code": "MR" },
    { "CountryName": "Mauritius", "Code": "MU" },
    { "CountryName": "Mayotte", "Code": "YT" },
    { "CountryName": "Mexico", "Code": "MX" },
    { "CountryName": "Micronesia (Federated States of)", "Code": "FM" },
    { "CountryName": "Moldova (Republic of)", "Code": "MD" },
    { "CountryName": "Monaco", "Code": "MC" },
    { "CountryName": "Mongolia", "Code": "MN" },
    { "CountryName": "Montenegro", "Code": "ME" },
    { "CountryName": "Montserrat", "Code": "MS" },
    { "CountryName": "Morocco", "Code": "MA" },
    { "CountryName": "Mozambique", "Code": "MZ" },
    { "CountryName": "Myanmar", "Code": "MM" },
    { "CountryName": "Namibia", "Code": "NA" },
    { "CountryName": "Nauru", "Code": "NR" },
    { "CountryName": "Nepal", "Code": "NP" },
    { "CountryName": "Netherlands", "Code": "NL" },
    { "CountryName": "New Caledonia", "Code": "NC" },
    { "CountryName": "New Zealand", "Code": "NZ" },
    { "CountryName": "Nicaragua", "Code": "NI" },
    { "CountryName": "Niger", "Code": "NE" },
    { "CountryName": "Nigeria", "Code": "NG" },
    { "CountryName": "Niue", "Code": "NU" },
    { "CountryName": "Norfolk Island", "Code": "NF" },
    { "CountryName": "Northern Mariana Islands", "Code": "MP" },
    { "CountryName": "Norway", "Code": "NO" },
    { "CountryName": "Oman", "Code": "OM" },
    { "CountryName": "Pakistan", "Code": "PK" },
    { "CountryName": "Palau", "Code": "PW" },
    { "CountryName": "Palestine, State of", "Code": "PS" },
    { "CountryName": "Panama", "Code": "PA" },
    { "CountryName": "Papua New Guinea", "Code": "PG" },
    { "CountryName": "Paraguay", "Code": "PY" },
    { "CountryName": "Peru", "Code": "PE" },
    { "CountryName": "Philippines", "Code": "PH" },
    { "CountryName": "Pitcairn", "Code": "PN" },
    { "CountryName": "Poland", "Code": "PL" },
    { "CountryName": "Portugal", "Code": "PT" },
    { "CountryName": "Puerto Rico", "Code": "PR" },
    { "CountryName": "Qatar", "Code": "QA" },
    { "CountryName": "Réunion", "Code": "RE" },
    { "CountryName": "Romania", "Code": "RO" },
    { "CountryName": "Russian Federation", "Code": "RU" },
    { "CountryName": "Rwanda", "Code": "RW" },
    { "CountryName": "Saint Barthélemy", "Code": "BL" },
    { "CountryName": "Saint Helena, Ascension and Tristan da Cunha", "Code": "SH" },
    { "CountryName": "Saint Kitts and Nevis", "Code": "KN" },
    { "CountryName": "Saint Lucia", "Code": "LC" },
    { "CountryName": "Saint Martin (French part)", "Code": "MF" },
    { "CountryName": "Saint Pierre and Miquelon", "Code": "PM" },
    { "CountryName": "Saint Vincent and the Grenadines", "Code": "VC" },
    { "CountryName": "Samoa", "Code": "WS" },
    { "CountryName": "San Marino", "Code": "SM" },
    { "CountryName": "Sao Tome and Principe", "Code": "ST" },
    { "CountryName": "Saudi Arabia", "Code": "SA" },
    { "CountryName": "Senegal", "Code": "SN" },
    { "CountryName": "Serbia", "Code": "RS" },
    { "CountryName": "Seychelles", "Code": "SC" },
    { "CountryName": "Sierra Leone", "Code": "SL" },
    { "CountryName": "Singapore", "Code": "SG" },
    { "CountryName": "Sint Maarten (Dutch part)", "Code": "SX" },
    { "CountryName": "Slovakia", "Code": "SK" },
    { "CountryName": "Slovenia", "Code": "SI" },
    { "CountryName": "Solomon Islands", "Code": "SB" },
    { "CountryName": "Somalia", "Code": "SO" },
    { "CountryName": "South Africa", "Code": "ZA" },
    { "CountryName": "South Georgia and the South Sandwich Islands", "Code": "GS" },
    { "CountryName": "South Sudan", "Code": "SS" },
    { "CountryName": "Spain", "Code": "ES" },
    { "CountryName": "Sri Lanka", "Code": "LK" },
    { "CountryName": "Sudan", "Code": "SD" },
    { "CountryName": "Suriname", "Code": "SR" },
    { "CountryName": "Svalbard and Jan Mayen", "Code": "SJ" },
    { "CountryName": "Swaziland", "Code": "SZ" },
    { "CountryName": "Sweden", "Code": "SE" },
    { "CountryName": "Switzerland", "Code": "CH" },
    { "CountryName": "Syrian Arab Republic", "Code": "SY" },
    { "CountryName": "Taiwan, Province of China", "Code": "TW" },
    { "CountryName": "Tajikistan", "Code": "TJ" },
    { "CountryName": "Tanzania, United Republic of", "Code": "TZ" },
    { "CountryName": "Thailand", "Code": "TH" },
    { "CountryName": "Timor-Leste", "Code": "TL" },
    { "CountryName": "Togo", "Code": "TG" },
    { "CountryName": "Tokelau", "Code": "TK" },
    { "CountryName": "Tonga", "Code": "TO" },
    { "CountryName": "Trinidad and Tobago", "Code": "TT" },
    { "CountryName": "Tunisia", "Code": "TN" },
    { "CountryName": "Turkey", "Code": "TR" },
    { "CountryName": "Turkmenistan", "Code": "TM" },
    { "CountryName": "Turks and Caicos Islands", "Code": "TC" },
    { "CountryName": "Tuvalu", "Code": "TV" },
    { "CountryName": "Uganda", "Code": "UG" },
    { "CountryName": "Ukraine", "Code": "UA" },
    { "CountryName": "United Arab Emirates", "Code": "AE" },
    { "CountryName": "United Kingdom of Great Britain and Northern Ireland", "Code": "GB" },
    { "CountryName": "United States Minor Outlying Islands", "Code": "UM" },
    { "CountryName": "United States of America", "Code": "US" },
    { "CountryName": "Uruguay", "Code": "UY" },
    { "CountryName": "Uzbekistan", "Code": "UZ" },
    { "CountryName": "Vanuatu", "Code": "VU" },
    { "CountryName": "Venezuela (Bolivarian Republic of)", "Code": "VE" },
    { "CountryName": "Viet Nam", "Code": "VN" },
    { "CountryName": "Virgin Islands (British)", "Code": "VG" },
    { "CountryName": "Virgin Islands (U.S.)", "Code": "VI" },
    { "CountryName": "Wallis and Futuna", "Code": "WF" },
    { "CountryName": "Western Sahara", "Code": "EH" },
    { "CountryName": "Yemen", "Code": "YE" },
    { "CountryName": "Zambia", "Code": "ZM" },
    { "CountryName": "Zimbabwe", "Code": "ZW" }
]

export default countries